### ISSUE TITLE
Problem when I try to open program

### ISSUE THREAD

**Issue by r4f4l** [kharts/plugin.video.ua-tv#1]
Privet kharts. I want to run it in my kodi but I have such troubles:
kodi.log

20:14:32 T:140246615164672  NOTICE: Thread LanguageInvoker start, auto delete: false
20:14:32 T:140246615164672  NOTICE: -->Python Interpreter Initialized<--
20:14:32 T:140245421840128  NOTICE: Thread BackgroundLoader start, auto delete: false
20:14:37 T:140245421840128  NOTICE: Thread LanguageInvoker start, auto delete: false
20:14:38 T:140245421840128  NOTICE: -->Python Interpreter Initialized<--
20:14:39 T:140245421840128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('items',)
                                            Traceback (most recent call last):
                                              File "/home/rafal/.kodi/addons/plugin.video.ua-tv/default.py", line 26, in <module>
                                                uatv.start()
                                              File "/home/rafal/.kodi/addons/plugin.video.ua-tv/resources/lib/uatv.py", line 51, in start
                                                open_channel(params["channel_id"][0])
                                              File "/home/rafal/.kodi/addons/plugin.video.ua-tv/resources/lib/uatv.py", line 82, in open_channel
                                                open_youtube_channel(channel)
                                              File "/home/rafal/.kodi/addons/plugin.video.ua-tv/resources/lib/uatv.py", line 104, in open_youtube_channel
                                                youtube_channel_id = get_channel_id_by_username(username)
                                              File "/home/rafal/.kodi/addons/plugin.video.ua-tv/resources/lib/uatv.py", line 173, in get_channel_id_by_username
                                                if response["items"]:
                                            KeyError: ('items',)
                                            -->End of Python script error report<--

I have youtube 5.1.16 by bromix installed & enabled. What's the problem.

**Comment by kharts** [comment]
Thanks for the report.
It seems it is YouTube plugin issue. I will investigate it and share results if I find any solutions.
In any case I'll fix an error - even if youtube returns noting, we shouldn't fail.

**Comment by r4f4l** [comment]
I've checked how plugin works in newer version YouTube plugin 5.1.18 but problems still exists. In addition when you try to open "Ukraina" channel there is info: No active live streams. Maybe update is really needed. ICTV informes internet transmission  it's not available. That's all. No chances to watch ukrainian TV in kodi at the moment :/
